services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    volumes:
      - ./Frontend/src:/app/src
      - /app/node_modules
    ports:
      - "5173:80"
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
