services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    volumes:
      - ./Frontend/src:/app/src
      - /app/node_modules
    ports:
      - "5173:80"
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend/src:/app/src
    ports:
      - "5050:5050"
